/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#faf9f7',
        'inverse-surface': '#2f3130',
        'on-primary-container': '#ceb6ff',
        tertiary: '#672023',
        'surface-container-low': '#f4f3f1',
        'primary-fixed': '#eaddff',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#ffacab',
        outline: '#7a7582',
        'on-primary-fixed': '#25005a',
        'on-secondary-fixed': '#211045',
        'surface-variant': '#e3e2e0',
        background: '#faf9f7',
        'secondary-fixed': '#e9ddff',
        'on-surface-variant': '#494551',
        'primary-container': '#5b3e96',
        'inverse-on-surface': '#f1f1ef',
        'surface-tint': '#6a4ea6',
        'tertiary-fixed-dim': '#ffb3b2',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e3e2e0',
        'on-secondary-container': '#5b4b82',
        'primary-fixed-dim': '#d2bcff',
        'on-tertiary-fixed': '#3f0209',
        'on-primary-fixed-variant': '#52358d',
        'tertiary-fixed': '#ffdad9',
        'inverse-primary': '#d2bcff',
        'tertiary-container': '#853638',
        'secondary-fixed-dim': '#d0bdfb',
        primary: '#43257d',
        'surface-container': '#efeeec',
        'on-error': '#ffffff',
        'secondary-container': '#d2c0fe',
        'surface-container-high': '#e9e8e6',
        secondary: '#65558c',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#7a2d30',
        surface: '#faf9f7',
        'on-secondary': '#ffffff',
        'on-surface': '#1a1c1b',
        'surface-dim': '#dadad8',
        'on-background': '#1a1c1b',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#4d3e73',
        'outline-variant': '#cbc4d2',
        // Dark mode surfaces
        'dark-surface': '#12141a',
        'dark-surface-container': '#1e2028',
        'dark-surface-container-low': '#181a22',
        'dark-surface-container-high': '#252830',
        'dark-surface-container-lowest': '#0d0f14',
        'dark-on-surface': '#e2e2df',
        'dark-on-surface-variant': '#c9c5d0',
        'dark-outline-variant': '#45434d',
        'dark-primary': '#d2bcff',
        'dark-on-primary': '#3b1e73',
        'dark-primary-container': '#52358d',
        'dark-secondary': '#d0bdfb',
        'dark-secondary-container': '#4d3e73',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '20px',
        'margin-desktop': '48px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        gutter: '24px',
        unit: '8px',
        'stack-md': '16px',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        spin: 'spin 1s linear infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      boxShadow: {
        'auth-card': '0 10px 40px -10px rgba(67, 37, 125, 0.05)',
        'auth-card-dark': '0 10px 40px -10px rgba(0, 0, 0, 0.4)',
        'primary-glow': '0 4px 24px rgba(67, 37, 125, 0.3)',
      },
      backgroundImage: {
        // Replaces the .hero-gradient inline <style> class from the original HTML.
        // Usage: className="bg-hero-gradient"
        'hero-gradient':
          'radial-gradient(circle at 70% 30%, rgba(210, 188, 255, 0.15) 0%, transparent 50%), ' +
          'radial-gradient(circle at 10% 80%, rgba(255, 179, 178, 0.1) 0%, transparent 40%)',
      },
      gridTemplateColumns: {
        // Allows grid-cols-12 for the bento layout.
        // Replaces the custom .bento-grid { grid-template-columns: repeat(12, 1fr) } CSS class.
        12: 'repeat(12, minmax(0, 1fr))',
      },
    },
  },
  plugins: [],
};
