/**
 * expense.mock.ts — Mock data for the FinanceHer Expenses Module
 *
 * All data is static and lives here as the single source of truth for the UI.
 *
 * AI INTEGRATION POINT: Replace these exports with API calls from
 * `src/services/expense.service.ts` when the backend is ready.
 * The type contracts (Transaction[], MonthlySummary, etc.) remain stable —
 * only the data source changes.
 */

import type {
  Transaction,
  MonthlySummary,
  CategoryBreakdown,
  ExpenseInsight,
} from '@/types/expense';

// ─── Transactions (current month: July 2026) ──────────────────────────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_001',
    name: 'Luminary Apartments',
    icon: 'home',
    category: 'Housing',
    isoDate: '2026-07-01',
    displayDate: 'Jul 1, 2026',
    amount: 22000,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Net Banking',
    accountId: '8812',
    note: 'Monthly rent — June cycle',
    isRecurring: true,
  },
  {
    id: 'txn_002',
    name: 'TechFlow Corp Salary',
    icon: 'work',
    category: 'Income',
    isoDate: '2026-07-01',
    displayDate: 'Jul 1, 2026',
    amount: 85000,
    type: 'income',
    status: 'Cleared',
    paymentMethod: 'ACH Transfer',
    accountId: '4201',
    isRecurring: true,
  },
  {
    id: 'txn_003',
    name: 'Swiggy',
    icon: 'restaurant',
    category: 'Dining',
    isoDate: '2026-06-30',
    displayDate: 'Jun 30, 2026',
    amount: 680,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'UPI',
    accountId: '9341',
    note: 'Dinner — late night craving',
  },
  {
    id: 'txn_004',
    name: 'Reliance Smart Bazaar',
    icon: 'shopping_cart',
    category: 'Groceries',
    isoDate: '2026-06-29',
    displayDate: 'Jun 29, 2026',
    amount: 3420,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Credit Card',
    accountId: '4920',
  },
  {
    id: 'txn_005',
    name: 'Uber',
    icon: 'commute',
    category: 'Transport',
    isoDate: '2026-06-28',
    displayDate: 'Jun 28, 2026',
    amount: 340,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'UPI',
    accountId: '9341',
  },
  {
    id: 'txn_006',
    name: 'Netflix Premium',
    icon: 'subscriptions',
    category: 'Subscriptions',
    isoDate: '2026-06-28',
    displayDate: 'Jun 28, 2026',
    amount: 649,
    type: 'expense',
    status: 'Recurring',
    paymentMethod: 'Credit Card',
    accountId: '4920',
    isRecurring: true,
  },
  {
    id: 'txn_007',
    name: 'Max Fashion',
    icon: 'shopping_bag',
    category: 'Shopping',
    isoDate: '2026-06-27',
    displayDate: 'Jun 27, 2026',
    amount: 2850,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Debit Card',
    accountId: '3301',
    note: 'Summer wardrobe',
  },
  {
    id: 'txn_008',
    name: 'BESCOM Electricity',
    icon: 'electric_bolt',
    category: 'Bills',
    isoDate: '2026-06-26',
    displayDate: 'Jun 26, 2026',
    amount: 1120,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Net Banking',
    accountId: '8812',
    isRecurring: true,
  },
  {
    id: 'txn_009',
    name: 'Apollo Pharmacy',
    icon: 'health_and_safety',
    category: 'Health',
    isoDate: '2026-06-25',
    displayDate: 'Jun 25, 2026',
    amount: 890,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'UPI',
    accountId: '9341',
  },
  {
    id: 'txn_010',
    name: 'BookMyShow — IMAX',
    icon: 'movie',
    category: 'Entertainment',
    isoDate: '2026-06-24',
    displayDate: 'Jun 24, 2026',
    amount: 950,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Credit Card',
    accountId: '4920',
  },
  {
    id: 'txn_011',
    name: 'Zepto Groceries',
    icon: 'shopping_cart',
    category: 'Groceries',
    isoDate: '2026-06-23',
    displayDate: 'Jun 23, 2026',
    amount: 1280,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'UPI',
    accountId: '9341',
  },
  {
    id: 'txn_012',
    name: 'Namma Metro',
    icon: 'train',
    category: 'Transport',
    isoDate: '2026-06-22',
    displayDate: 'Jun 22, 2026',
    amount: 180,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Wallet',
    accountId: 'NMRC',
  },
  {
    id: 'txn_013',
    name: 'Spotify Premium',
    icon: 'music_note',
    category: 'Subscriptions',
    isoDate: '2026-06-21',
    displayDate: 'Jun 21, 2026',
    amount: 119,
    type: 'expense',
    status: 'Recurring',
    paymentMethod: 'Credit Card',
    accountId: '4920',
    isRecurring: true,
  },
  {
    id: 'txn_014',
    name: 'Freelance — UI Design',
    icon: 'palette',
    category: 'Income',
    isoDate: '2026-06-20',
    displayDate: 'Jun 20, 2026',
    amount: 18000,
    type: 'income',
    status: 'Cleared',
    paymentMethod: 'Net Banking',
    accountId: '7719',
    note: 'Invoice #FH-2026-07',
  },
  {
    id: 'txn_015',
    name: 'Taj Vivanta — Dinner',
    icon: 'restaurant',
    category: 'Dining',
    isoDate: '2026-06-19',
    displayDate: 'Jun 19, 2026',
    amount: 3600,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Credit Card',
    accountId: '4920',
    note: 'Team celebration dinner',
  },
  {
    id: 'txn_016',
    name: 'Axis Mutual Fund SIP',
    icon: 'trending_up',
    category: 'Investments',
    isoDate: '2026-06-18',
    displayDate: 'Jun 18, 2026',
    amount: 10000,
    type: 'expense',
    status: 'Recurring',
    paymentMethod: 'ACH Transfer',
    accountId: '5521',
    isRecurring: true,
  },
  {
    id: 'txn_017',
    name: 'Jio Fiber',
    icon: 'wifi',
    category: 'Bills',
    isoDate: '2026-06-17',
    displayDate: 'Jun 17, 2026',
    amount: 999,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Direct Debit',
    accountId: '8812',
    isRecurring: true,
  },
  {
    id: 'txn_018',
    name: 'Udemy — React Course',
    icon: 'school',
    category: 'Education',
    isoDate: '2026-06-16',
    displayDate: 'Jun 16, 2026',
    amount: 449,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'Credit Card',
    accountId: '4920',
    note: 'Advanced React Patterns',
  },
  {
    id: 'txn_019',
    name: 'IndiGo — Goa Return',
    icon: 'flight',
    category: 'Travel',
    isoDate: '2026-06-15',
    displayDate: 'Jun 15, 2026',
    amount: 5600,
    type: 'expense',
    status: 'Pending',
    paymentMethod: 'Credit Card',
    accountId: '4920',
  },
  {
    id: 'txn_020',
    name: 'Barbeque Nation',
    icon: 'restaurant',
    category: 'Dining',
    isoDate: '2026-06-14',
    displayDate: 'Jun 14, 2026',
    amount: 1800,
    type: 'expense',
    status: 'Cleared',
    paymentMethod: 'UPI',
    accountId: '9341',
  },
];

// ─── Category Breakdowns ──────────────────────────────────────────────────────

export const MOCK_CATEGORY_BREAKDOWNS: CategoryBreakdown[] = [
  {
    category: 'Housing',
    totalAmount: 22000,
    percentage: 38,
    transactionCount: 1,
    icon: 'home',
    colorClass: 'bg-primary',
    strokeColor: '#43257d',
  },
  {
    category: 'Dining',
    totalAmount: 6080,
    percentage: 11,
    transactionCount: 3,
    icon: 'restaurant',
    colorClass: 'bg-[#E57373]',
    strokeColor: '#E57373',
  },
  {
    category: 'Groceries',
    totalAmount: 4700,
    percentage: 8,
    transactionCount: 2,
    icon: 'shopping_cart',
    colorClass: 'bg-emerald-500',
    strokeColor: '#10b981',
  },
  {
    category: 'Investments',
    totalAmount: 10000,
    percentage: 17,
    transactionCount: 1,
    icon: 'trending_up',
    colorClass: 'bg-secondary',
    strokeColor: '#65558c',
  },
  {
    category: 'Shopping',
    totalAmount: 2850,
    percentage: 5,
    transactionCount: 1,
    icon: 'shopping_bag',
    colorClass: 'bg-amber-500',
    strokeColor: '#f59e0b',
  },
  {
    category: 'Transport',
    totalAmount: 520,
    percentage: 1,
    transactionCount: 2,
    icon: 'commute',
    colorClass: 'bg-sky-500',
    strokeColor: '#0ea5e9',
  },
  {
    category: 'Bills',
    totalAmount: 2119,
    percentage: 4,
    transactionCount: 2,
    icon: 'electric_bolt',
    colorClass: 'bg-orange-500',
    strokeColor: '#f97316',
  },
  {
    category: 'Other',
    totalAmount: 9531,
    percentage: 16,
    transactionCount: 8,
    icon: 'more_horiz',
    colorClass: 'bg-outline',
    strokeColor: '#7a7582',
  },
];

// ─── Monthly Summary ──────────────────────────────────────────────────────────

export const MOCK_MONTHLY_SUMMARY: MonthlySummary = {
  monthKey: '2026-06',
  label: 'June 2026',
  totalExpenses: 57800,
  totalIncome: 103000,
  netCashFlow: 45200,
  savingsAmount: 10000,
  savingsRate: 0.097,
  expenseDeltaPercent: -8.2,
  budgetLimit: 65000,
  budgetUtilisationPercent: 78,
  categoryBreakdowns: MOCK_CATEGORY_BREAKDOWNS,
  transactions: MOCK_TRANSACTIONS,
};

// ─── Historical Data (for trend chart) ───────────────────────────────────────

/**
 * AI INTEGRATION POINT: This data drives the trend chart and will feed the AI
 * month-over-month analysis. Replace with GET /api/expenses/summary?months=6.
 */
export const MOCK_MONTHLY_TREND = [
  { month: 'Jan', expenses: 61200, income: 85000, savings: 8000 },
  { month: 'Feb', expenses: 54000, income: 85000, savings: 12000 },
  { month: 'Mar', expenses: 63000, income: 103000, savings: 10000 },
  { month: 'Apr', expenses: 58400, income: 103000, savings: 14000 },
  { month: 'May', expenses: 62900, income: 103000, savings: 9500 },
  { month: 'Jun', expenses: 57800, income: 103000, savings: 10000 },
];

// ─── AI-ready Insights ────────────────────────────────────────────────────────

/**
 * Rule-based insights stubs. These mimic the shape the AI will return.
 *
 * AI INTEGRATION POINT: Replace with GET /api/insights?userId=... when the
 * Gemini RAG pipeline is integrated. The `isAIGenerated` flag will flip to
 * `true` for AI-produced insights.
 */
export const MOCK_INSIGHTS: ExpenseInsight[] = [
  {
    id: 'ins_001',
    title: 'Dining spend is 3× last month',
    body: 'You spent ₹6,080 on dining in June — up from ₹2,100 in May. Consider meal-prepping 2–3 days a week to cut this by ₹2,000.',
    severity: 'warning',
    icon: 'restaurant',
    dataRefs: ['txn_003', 'txn_015', 'txn_020'],
    isAIGenerated: false,
  },
  {
    id: 'ins_002',
    title: 'Great job on investments!',
    body: 'Your ₹10,000 SIP was auto-debited on time. At this pace, your mutual fund corpus grows to ₹6.2L in 5 years at 12% p.a.',
    severity: 'success',
    icon: 'trending_up',
    dataRefs: ['txn_016'],
    isAIGenerated: false,
  },
  {
    id: 'ins_003',
    title: 'Flight booking is Pending',
    body: 'Your ₹5,600 IndiGo booking is still pending. If it fails, the amount will be refunded in 5–7 business days.',
    severity: 'info',
    icon: 'flight',
    dataRefs: ['txn_019'],
    isAIGenerated: false,
  },
  {
    id: 'ins_004',
    title: 'Budget on track',
    body: 'You\'ve used 78% of your ₹65,000 June budget with 3 days remaining. You\'re projected to finish under budget — well done!',
    severity: 'tip',
    icon: 'savings',
    dataRefs: [],
    isAIGenerated: false,
  },
];

// ─── Constants ────────────────────────────────────────────────────────────────

export const EXPENSE_CATEGORIES = [
  'All',
  'Housing',
  'Dining',
  'Groceries',
  'Transport',
  'Shopping',
  'Entertainment',
  'Bills',
  'Health',
  'Education',
  'Travel',
  'Subscriptions',
  'Investments',
  'Income',
  'Other',
] as const;

export const PAYMENT_METHODS = [
  'Credit Card',
  'Debit Card',
  'UPI',
  'Net Banking',
  'Cash',
  'ACH Transfer',
  'Apple Pay',
  'Direct Debit',
  'Wallet',
] as const;

export const ITEMS_PER_PAGE = 8;
