/**
 * assistant.ts — FinanceHer AI Assistant Module Types
 *
 * These types form the data contract for the AI Assistant chat interface.
 * Designed so the mock layer can be replaced with a live Gemini API call
 * with zero component changes.
 *
 * AI INTEGRATION POINT: When the Gemini backend is ready, replace
 * MOCK_CONVERSATIONS and MOCK_AI_RECOMMENDATIONS with:
 *   POST /api/assistant/message  → AIMessage (streamed)
 *   GET  /api/assistant/history  → ConversationSession[]
 *   GET  /api/assistant/insights → AIRecommendation[]
 */

// ─── Message ─────────────────────────────────────────────────────────────────

export type MessageRole = 'user' | 'assistant';

/** Type of rich content the assistant can embed inside a message. */
export type AssistantCardType =
  | 'metric'       // Single KPI figure (e.g. rent ratio 36%)
  | 'progress'     // Progress bar (e.g. emergency fund 75%)
  | 'comparison'   // Two-column before/after or A vs B
  | 'list'         // Bulleted data list
  | 'chart-ref';   // Placeholder referencing a dashboard chart

/**
 * Optional rich data card embedded inside an assistant message.
 *
 * AI INTEGRATION POINT: The Gemini response will include a `card` payload
 * when it detects that the query is best answered with structured data.
 * The card type determines which component renders it.
 */
export interface AssistantCard {
  type: AssistantCardType;
  title: string;
  /** Flexible key-value payload — shape depends on `type`. */
  data: Record<string, string | number | boolean>;
}

/** Suggested follow-up action button rendered below an assistant message. */
export interface MessageAction {
  id: string;
  label: string;
  icon: string;
  /** The prompt text to pre-fill in the input when clicked. */
  promptText: string;
}

/**
 * A single message in the chat thread.
 *
 * AI INTEGRATION POINT: When streaming is connected, add a `isStreaming`
 * flag and render the `content` incrementally via a typewriter effect.
 */
export interface AIMessage {
  id: string;
  role: MessageRole;
  /** Main markdown-compatible text content. */
  content: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
  /** Human-readable time label (e.g., "9:41 AM"). */
  displayTime: string;
  /**
   * Rich data card embedded in the message.
   * AI INTEGRATION POINT: Populated by Gemini when query demands structured data.
   */
  card?: AssistantCard;
  /** Follow-up action buttons rendered below this message. */
  actions?: MessageAction[];
  /**
   * Whether this message was generated by the AI layer.
   * false = static mock; true = live Gemini output.
   */
  isAIGenerated: boolean;
}

// ─── Conversation Session ─────────────────────────────────────────────────────

/**
 * A single historical conversation session.
 *
 * AI INTEGRATION POINT: Replace MOCK_CONVERSATION_HISTORY with
 * GET /api/assistant/history when backend is ready.
 */
export interface ConversationSession {
  id: string;
  title: string;
  /** ISO 8601 date string of the last message. */
  lastMessageAt: string;
  displayDate: string;
  /** Preview of the last message in the session. */
  preview: string;
  messageCount: number;
  /** Category tag for grouping in the history sidebar. */
  category: 'budgeting' | 'goals' | 'investing' | 'general' | 'expenses';
}

// ─── Suggested Prompt ─────────────────────────────────────────────────────────

/**
 * A quick-action prompt chip shown below the input bar.
 * Clicking a chip pre-fills the input.
 */
export interface SuggestedPrompt {
  id: string;
  label: string;
  icon: string;
  promptText: string;
  category: 'budgeting' | 'goals' | 'investing' | 'general' | 'expenses';
}

// ─── AI Recommendation Card ───────────────────────────────────────────────────

export type RecommendationSeverity = 'info' | 'warning' | 'success' | 'tip';

/**
 * A proactive AI recommendation surfaced in the sidebar panel.
 *
 * AI INTEGRATION POINT: Replace MOCK_AI_RECOMMENDATIONS with
 * GET /api/assistant/insights when Gemini is connected.
 * Flip `isAIGenerated` to true and show the AI badge.
 */
export interface AIRecommendation {
  id: string;
  title: string;
  body: string;
  severity: RecommendationSeverity;
  icon: string;
  /** Module this recommendation relates to. */
  sourceModule: 'expenses' | 'goals' | 'budget' | 'general';
  isAIGenerated: boolean;
}

// ─── Chat Input State ─────────────────────────────────────────────────────────

/**
 * UI state for the chat input area.
 * Kept as a single object for easy serialisation (future draft persistence).
 */
export interface ChatInputState {
  text: string;
  isRecording: boolean;
  isSending: boolean;
}
